version: '3'

services:
  grocery-service:
    image: shared-grocery/grocery-service:${GROCERY_SERVICE_TAG}
    links:
     - mssql-server

  mssql-server:
    image: shared-grocery/mssql-server:${MSSQL_SERVER_TAG}
