version: '3'

services:
  grocery-service:
    image: whojoo/grocery-service:${GROCERY_SERVICE_TAG}
    links:
     - mssql-server

  mssql-server:
    image: whojoo/grocery-service-mssql:${MSSQL_SERVER_TAG}
    volumes:
      - mssql-data:/var/lib/db

volumes:
  mssql-data:
