version: '3'

services:
  grocery-service:
    image: whojoo/grocery-service:${GROCERY_SERVICE_TAG}
    links:
      - grocery-data
      - uaa-data
      - config-server
    depends_on:
      - config-server
      - grocery-data
      - uaa-data
  
  grocery-data:
    image: postgres:${GROCERY_DATA_POSTGRES_TAG}
    volumes:
      - grocery-data:/var/lib/postgresql/data

  uaa-data:
    image: postgres:${UAA_DATA_POSTGRES_TAG}
    volumes:
      - uaa-data:/var/lib/postgresql/data

  config-server:
<<<<<<< HEAD
    image: hyness/spring-cloud-config-server:${CONFG_SERVER_TAG}
    volumes:
      - ./config-server:/config
    env_file:
      - config-server.env
    ports:
      - "8888:8888"
=======
    image: hyness/spring-cloud-config-server:${CONFIG_SERVER_TAG}
    env_file:
      - config-server.env
>>>>>>> develop

volumes:
  grocery-data:
  uaa-data:
