version: '3'

services:
  grocery-service:
    build:
      context: ./SharedGrocery
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNSTR_DefaultConnection=Data Source=localhost,1433;Initial Catalog=groceries;Integrated Security=False;User ID=sa;Password=Passw0rd
    ports:
      - "8000:80"

  mssql-server:
    build:
      context: ./mssql-server
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=Passw0rd
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

