version: '3'

services:
  grocery-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "8000:80"
  
  grocery-data:
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=groceries
  
  uaa-data:
    ports:
      - "5433:5432"
    environment: 
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=uaa

  config-server:
    volumes:
      - ./config-server:/config
    ports:
      - "8888:8888"
