version: '3'

services:
  grocery-service:
    build:
      context: ./SharedGrocery
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:Groceries=Data Source=mssql-server,1433;Initial Catalog=groceries;Integrated Security=False;User ID=sa;Password=Passw0rd
      - ConnectionStrings:Uaa=Data Source=uaa-mssql,1433;Initial Catalog=uaa;Integrated Security=False;User ID=sa;Password=Passw0rd
    ports:
      - "8000:80"

  mssql-server:
    build:
      context: ./mssql-server
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=Passw0rd
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  uaa-mssql:
    build:
      context: ./mssql-server
      dockerfile: Dockerfile
    environment:
      - SA_PASSWORD=Passw0rd
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"

