version: '3'

services:
  grocery-service:
    build:
      context: ./SharedGrocery
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:Groceries=Data Source=grocery-data,1433;Initial Catalog=groceries;Integrated Security=False;User ID=sa;Password=Passw0rd
      - ConnectionStrings:Uaa=Data Source=uaa-data,1433;Initial Catalog=uaa;Integrated Security=False;User ID=sa;Password=Passw0rd
    ports:
      - "8000:80"
  
  grocery-data:
    build:
      context: ./postgres-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=groceries
  
  uaa-data:
    build:
      context: ./postgres-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5433:5432"
    environment: 
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=uaa
