version: '3'

services:
  grocery-service:
    image: whojoo/grocery-service:${GROCERY_SERVICE_TAG}
    links:
      - grocery-data
      - uaa-data
    env_file:
      - secrets.env
  
  grocery-data:
    image: whojoo/grocery-data-postgres:${GROCERY_DATA_POSTGRES_TAG}
    volumes:
      - grocery-data:/var/lib/postgresql/data

  uaa-data:
    image: whojoo/uaa-data-postgres:${UAA_DATA_POSTGRES_TAG}
    volumes:
      - uaa-data:/var/lib/postgresql/data

  config-server:
    image: hyness/spring-cloud-config-server:${CONFG_SERVER_TAG}
    volumes:
      - ./config-server:/config
    env_file:
      - config-server.env
    ports:
      - "8888:8888"

volumes:
  grocery-data:
  uaa-data:
