// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using SharedGrocery.Repositories.DBContexts;
using System;

namespace SharedGrocery.Migrations
{
    [DbContext(typeof(GroceryDataContext))]
    [Migration("20180206195354_GroceryListAndGroceriesManyToMany")]
    partial class GroceryListAndGroceriesManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview1-24937")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SharedGrocery.Models.Grocery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groceries");
                });

            modelBuilder.Entity("SharedGrocery.Models.GroceryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("SharedGrocery.Models.Joins.GroceryListGrocery", b =>
                {
                    b.Property<int>("GroceryId");

                    b.Property<int>("GroceryListId");

                    b.HasKey("GroceryId", "GroceryListId");

                    b.HasIndex("GroceryListId");

                    b.ToTable("GroceryListGrocery");
                });

            modelBuilder.Entity("SharedGrocery.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SharedGrocery.Models.GroceryList", b =>
                {
                    b.HasOne("SharedGrocery.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("SharedGrocery.Models.Joins.GroceryListGrocery", b =>
                {
                    b.HasOne("SharedGrocery.Models.Grocery", "Grocery")
                        .WithMany("GroceryListGroceries")
                        .HasForeignKey("GroceryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SharedGrocery.Models.GroceryList", "GroceryList")
                        .WithMany("GroceryListGroceries")
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
        }
    }
}
